pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
        - author=dependabot[bot]
        - author=github-actions[bot]
      - label=dependencies

      - check-success=COSMIC x86_64 Live ISO
      - check-success=COSMIC AArch64 Live ISO
    actions:
      merge:
        method: squash
      delete_head_branch:
