name: "COSMIC Live ISO"
on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - .github/workflows/cosmic.yml
  pull_request:
    branches:
      - main
    paths:
      - flake.nix
      - .github/workflows/cosmic.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - system: x86_64-linux
            runner: ubuntu-latest
            name: x86_64
          - system: aarch64-linux
            runner: [ linux, ARM64, drakon64/github-actions-runner-aws, EC2-c8g.xlarge, EBS-30GB ]
            name: AArch64

    name: COSMIC ${{ matrix.architecture.name }} Live ISO
    runs-on: ${{ matrix.architecture.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v29

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-cosmic-iso
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: cosmic

      - env:
          SYSTEM: ${{ matrix.architecture.system }}
        run: nix build --system "$SYSTEM" .#cosmicIso.closure

      - run: |
          ISO_FILE=(result/iso/*.iso)
          echo ISO_FILE=$ISO_FILE >> $GITHUB_ENV
          echo ISO_NAME=$(echo "$ISO_FILE" | sed -e 's/result\/iso\///' -e 's/.iso$//') >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: ${{ env.ISO_FILE }}
          compression-level: 0
          if-no-files-found: error
        if: github.ref == 'refs/heads/main'
