name: Flake

on:
  schedule:
#    - cron: '0 7 * * *'
    - cron: '0 13 * * *' # Six hours after upstream
  workflow_dispatch:

jobs:
  update:
    name: Flake Update
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          commit-msg: 'flake: update inputs'
          pr-title: 'flake: update inputs'
          pr-labels: 'dependencies'

      - uses: benc-uk/workflow-dispatch@v1
        if: ${{ contains(fromJSON('["created", "updated"]'), steps.update-flake-lock.outputs.pull-request-operation) }}
        with:
          workflow: cosmic.yml
          ref: refs/heads/ac652952b2badccf2d81413ed14ae7ff89190ae1
